import os
import pandas as pd

metadata = pd.read_table("files/samples/sample_barcode.txt", sep = "\t")

SAMPLES = metadata["sample_seq_id"].unique().tolist()
BARCODES = metadata["sample_barcode"].unique().tolist()
CUTOFF = 2500000
SEQTK_SEED = 100
METAPHLAN_DB = "/home/projects/cu_00014/data/databases/metaphlan_4.1.0" #/home/projects/cu_00014/data/databases/ #/services/tools/metaphlan/4.0.3/lib/python3.10/site-packages/metaphlan/metaphlan_databases
METAPHLAN_INDEX = "mpa_vJun23_CHOCOPhlAnSGB_202307" #"mpa_vJan21_CHOCOPhlAnSGB_202103"

TMP_DIR = "/home/projects/cu_00014/scratch/"
OUT_DIR = "data/micropouch/metaphlan4/"

include: "rules/FunctionsModule.smk"

if os.path.exists(OUT_DIR+"fastqs_NonHuman_ReadCount.txt"):
    SUBSAMPLED_BARCODES = getSubSamples(OUT_DIR+"fastqs_NonHuman_ReadCount.txt",CUTOFF)
else:
    SUBSAMPLED_BARCODES = BARCODES

include: "rules/fastp.smk"
include: "rules/BowtieRemoveHuman.smk"
include: "rules/ConcatenateSamples.smk"
include: "rules/Subsampling.smk"
include: "rules/metaphlan.smk"


def RuleAll(metadata):
    rule_all_input = []

    
    for barcode in BARCODES:
        
        for sample in SAMPLES:
            rule_all_input.append(OUT_DIR+barcode+"/fastp/"+sample+"_R1_fastp.fastq")
            rule_all_input.append(OUT_DIR+barcode+"/fastp/"+sample+"_R2_fastp.fastq")
            rule_all_input.append(OUT_DIR+barcode+"/"+sample+"_R1_NonHuman.fastq.gz")
            rule_all_input.append(OUT_DIR+barcode+"/"+sample+"_R2_NonHuman.fastq.gz")
            rule_all_input.append(OUT_DIR+barcode+"/"+sample+"_NonHuman_ReadCount.txt")
        
        
    if os.path.exists(OUT_DIR+"fastqs_NonHuman_ReadCount.txt"):
        barcodes = getSubSamples(OUT_DIR+"fastqs_NonHuman_ReadCount.txt",CUTOFF)
        for barcode in barcodes:
            rule_all_input.append(OUT_DIR+barcode+"/"+barcode+"_R1_NonHuman_Combined.fastq.gz")
            rule_all_input.append(OUT_DIR+barcode+"/"+barcode+"_R2_NonHuman_Combined.fastq.gz")
            rule_all_input.append(OUT_DIR+barcode+"/"+barcode+"_R1_NonHuman_Combined_Subsampled_"+str(CUTOFF)+".fastq.gz")
            rule_all_input.append(OUT_DIR+barcode+"/"+barcode+"_R2_NonHuman_Combined_Subsampled_"+str(CUTOFF)+".fastq.gz")
            rule_all_input.append(OUT_DIR+barcode+"/"+barcode+"_NonHuman_Combined_Subsampled_"+str(CUTOFF)+"_profile.txt")


    rule_all_input.append(OUT_DIR+"fastqs_NonHuman_ReadCount.txt")
    rule_all_input.append(OUT_DIR+"MetaPhlAn_4.1.0_Combined_NonHuman_Subsampled_"+str(CUTOFF)+"_profile.txt")
    
    return rule_all_input



rule all:
    input:
        RuleAll(metadata)