---
title: "redo_libraries"
author: "Sebastian Mølvang Dall"
date: "30/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(ggpubr)
```


## Redo libraries into library 7,8

```{r}
ext_conc <- read_csv("../data/EXT_conc/EXT_ALL.csv") %>% 
  rename(patient = person,
         fecal_donation_number = batch_number) %>% 
  mutate(project = ifelse(grepl("PaPr", sample_barcode), "MP",
                          ifelse(grepl("PaOp", sample_barcode), "OP",
                                 ifelse(grepl("PaNP", sample_barcode), "NP", NA))))
```


#### Redoing bad libs

Isolating libraries with low amounts. and filtering away negatives

```{r}
neg <- c("C3", "F3", "C10", "F10", "E12", "F12", "D12")

Lib_b <- ext_conc %>% 
  filter(pool_ng < 1) %>% # Bad libs
  filter(!paste0(tube_row,tube_column) %in% neg) %>% # Removing negative+positive controls
  filter(ifelse(rack_barcode == "EXT00001", paste0(tube_row,tube_column) != "C12", TRUE)) %>% #Remove C12 from EXT0001
  arrange(rack_barcode, tube_column, tube_row) %>%  #Arrange for easy overview
  mutate(library_plate = ifelse(row_number() < 55, "LIB00007", "LIB00008"))
  

#Ark der viser hvilke prøver der skal pickes. new_col og new_row er blevet tilføjet manuelt i excel.
#write_csv(select(Lib_b, sample_barcode, rack_barcode, tube_row, tube_column, library_plate), file = "../data/LIB_redo/LIB_7_8_picking.csv") #Add new_row and new_column in excel
```


```{r}
lib7_8 <- read_csv("../data/LIB_redo/LIB_7_8_picking.csv") %>% 
  select(sample_barcode:new_column)

redo_7_8 <- lib7_8 %>% 
  select(!c(tube_row, tube_column)) %>% 
  left_join(ext_conc, by = c("sample_barcode", "rack_barcode"))

#write_csv(redo_7_8, "../data/LIB_redo/redo_7_8.csv")

```




## Checking result


```{r}
files_lib <- list.files("../data/LIB_redo/", full.names = T, pattern = "*.xlsx")
```

```{r}
lib_conc <- tibble()

for (f in files_lib) {
  lib_tmp <- read_excel(f, range = "A11:F105")
  
  lib_conc <- bind_rows(lib_conc, lib_tmp)
  
  
}


```

```{r}
lib_conc_c <- lib_conc %>%
  rename(lib_conc = `ng/µL`,
         library_plate = PlateID) %>%
  filter(!lib_conc < 0) %>%
  mutate(pool_ng = lib_conc * Vsample) %>%
  select(LibID, library_plate, WellID , lib_conc, pool_ng) %>%
  separate(WellID, sep ="(?<=[A-Za-z])(?=[0-9])", into = c("new_row", "new_column")) %>%
  mutate(new_column = as.numeric(new_column))
```


### read redo_lib78 file

```{r}
redo_7_8 <- read_csv("../data/LIB_redo/redo_7_8.csv")
```

#### Joing with lib_conc_c
```{r}
d_redo <- redo_7_8 %>% 
  select(-c("LibID", "pool_ng", "lib_conc")) %>% 
  full_join(lib_conc_c, redo_7_8, by = c("library_plate", "new_row", "new_column"))
```



## Join with ext_conc

```{r}
ext_tmp <- ext_conc %>% 
  mutate(library_plate = gsub("EXT", "LIB", rack_barcode)) %>% 
  filter(!barcode %in% filter(d_redo, !is.na(barcode))$barcode) %>% 
  bind_rows(d_redo) %>% 
  mutate(new_column = ifelse(is.na(new_column), tube_column, new_column),
         new_row = ifelse(is.na(new_row), tube_row, new_row)) %>% 
  filter(LibID != "LIB-MP001-C12")
```


```{r}
#write_csv(ext_tmp, file = "../data/metagenomes_lab/220531_metagenome_libraries.csv")
```

```{r}
gg_lib_b <- ext_conc %>% 
  filter(!is.na(lib_conc),
         LibID != "LIB-MP001-C12") %>% 
  mutate(pool_ng = round(pool_ng, 2),
         tube_row = fct_rev(tube_row)) %>% 
ggplot(aes(x = tube_column, y = tube_row, fill = pool_ng, label = pool_ng)) + 
  geom_tile(color = "white") +
  geom_text(color = "white") + 
  scale_fill_gradient(low = "red4", high = "green4") + 
  facet_wrap(.~rack_barcode) +
  scale_x_discrete(expand = c(0, 0),position = 'top')

```



```{r}
gg_lib_a <- ext_tmp %>% 
  filter(!is.na(lib_conc)) %>% 
  mutate(pool_ng = round(pool_ng, 2),
         new_row = fct_rev(new_row)) %>% 
ggplot(aes(x = new_column, y = new_row, fill = pool_ng, label = pool_ng)) + 
  geom_tile(color = "white") +
  geom_text(color = "white") + 
  scale_fill_gradient(low = "red4", high = "green4") + 
  facet_wrap(.~library_plate) +
  scale_x_discrete(expand = c(0, 0),position = 'top')

ggarrange(gg_lib_b, gg_lib_a, ncol = 1 )
```


Alot of libraries were saved by redoing them. The ones that fail probably cannot be rescued. So I will proceed.



```{r}
x <- ext_tmp %>% 
  filter(!is.na(lib_conc)) %>% 
  group_by(library_plate) %>% 
  summarise(samples = n())

```


# Pooling files

## pool 1

```{r}
libs <- unique(ext_tmp$library_plate)
libs <- grep("[7-8]", libs, invert = T, value = T)
```


```{r}
for (lib in libs) {
  pool <- ext_tmp %>% 
  filter(library_plate == lib) %>% 
  mutate(Vsample = pool_ng / lib_conc) %>% 
  select(sample_barcode, LibID, new_column, new_row, lib_conc, Vsample, pool_ng) %>% 
  arrange(new_column, new_row) %>% 
  mutate(source_well = paste0(new_row, new_column))

  
  #write_csv(pool, paste0("../data/metagenomes_lab/I-DOT pools/",lib,".csv"))
  
}



```





## Sanity check

```{r}
np <- ext_tmp %>% 
  filter(is.na(barcode)) %>% 
  group_by(library_plate) %>% 
  summarise(samples = n())


sp <- ext_tmp %>%
  group_by(library_plate) %>% 
  summarise(samples = n())

sp

length(unique(sp$barcode))
```


## Making illumina files:

```{r}
ill <- ext_tmp %>% 
  select(LibID, library_plate, new_row, new_column) %>% 
  mutate(Sample_ID = str_replace(LibID, "LIB", library_plate),
         new_column = as.character(new_column),
         new_column = if_else(str_length(new_column) == 1, true = paste0("0",new_column), false = new_column),
         index_well = paste0(new_row,new_column),
         sample = "sample") %>% 
  arrange(library_plate, new_column, new_row) %>% 
  select(Sample_ID, sample, index_well)


#write_csv(ill, "../data/metagenomes_lab/sample_sheet.csv")
```


