---
title: "ggplots for metadata"
author: "Sebastian Mølvang Dall"
date: '2022-06-22'
output: html_document
editor_options: 
  chunk_output_type: console
---


### Libraries

```{r}
library(tidyverse)
library(ggpubr)
source("functions/metadata_functions.R")
source("functions/gg_functions.R")
```



#### Stage factor

```{r}
stage_fct <- c("inclusion", 
         "treatment_5", 
         "treatment_10",
         "treatment_15",
         "treatment_21",
         "followup_30d",
         "followup_1m",
         "followup_3m",
         "followup_6m",
         "followup_12m",
         "drop_out")
```





### Load metadata file

```{r}
m <- mplibrary::load_metadata()
```

#### patient samples
```{r}
m_pt <- m %>% 
  filter(!is.na(sample_barcode), project %in% c("MP", "OP", "NP")) %>% 
  mutate(stage = factor(stage, levels = stage_fct, labels = stage_fct),
         pool_ng = round(pool_ng, 2)) %>% 
  arrange(id, project) %>% 
  fill(group, .direction = "down")
```



## Library preparation
```{r}
m_pt %>% 
  ggplot(aes(x = stage, y = id, fill = pool_ng, label = pool_ng)) + 
  geom_tile(color = "white") + 
  #geom_text(color = "black") + 
  scale_fill_gradient(low = "red4", high = "green4") + 
  #scale_fill_manual(values = c("red4", "blue4")) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1)) +
  facet_grid(. ~project, scales = "free_x", space = "free_x") + 
  #ggtitle("Samples with enough DNA for 20 ng input using 3 µl")+
  labs(y ="", x= "")
  
```


## DNA extraction concentration
```{r}
m_pt %>% 
  mutate(DNA_ng = round(ext_conc*80),
         above100 = DNA_ng >= 100) %>% 
  ggplot(aes(x = stage, y = id, fill = above100, label = DNA_ng)) + 
  geom_tile(color = "white") + 
  geom_text(color = "white") + 
  scale_fill_manual(values = c("red4", "blue4")) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1)) +
  facet_grid(group ~project, scales = "free", space = "free") + 
  labs(y ="", x= "")
  
```



## DNA extraction donor

```{r}
m %>% 
  filter(project == "donor_batch") %>% 
  mutate(DNA_ng = round(ext_conc*80),
         above100 = DNA_ng >= 100,
         donor_batch = paste0(id, "_", fecal_donation_number)) %>%
  ggplot(aes(x = as.factor(fecal_donation_number), y = id, fill = ext_conc, label = DNA_ng)) + 
  geom_tile(color = "white") + 
  geom_text(color = "white") + 
  scale_fill_gradient(low = "red4", high = "green4") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1)) +
  labs(y ="", x= "")
```





## patient donor pairing
```{r}
m_pt %>%
  filter(stage %in% c("treatment_5", "treatment_10", "treatment_15", "treatment_21"),
         !is.na(group)) %>% 
  select(id, stage, project, group, donor) %>%
  mutate(donor = parse_number(donor)) %>% 
  ggplot(aes(x = stage, y = id, fill = group, label = donor)) + 
  geom_tile(color="white") + 
  facet_grid(~project) + 
  geom_text(check_overlap = T) + 
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))

```



## PDAI score

```{r}
integer_breaks <- function(n = 5, ...) {
  fxn <- function(x) {
    breaks <- floor(pretty(x, n, ...))
    names(breaks) <- attr(breaks, "labels")
    breaks
  }
  return(fxn)
}
```


```{r}
m %>% 
  filter(stage %in% c("inclusion", "followup_30d"),
         str_detect(id, "pt"),
         project == "MP") %>% 
  group_by(id) %>%
  filter(n_distinct(stage) == 2) %>% 
  mutate(stage = factor(stage, levels = c("inclusion", "followup_30d"), labels = c("Before", "After"))) %>% 
  ggplot(aes(x = stage, y = pdai_score, color = stage)) +
  geom_boxplot(outlier.shape = NA) +
  geom_line(aes(group = id), alpha = 0.6, color = "grey70", position = position_dodge(0.2)) + 
  geom_point(aes(group = id), size = 2, position = position_dodge(0.2)) + 
  facet_wrap(.~group)+
  plot_theme + 
  labs(y = "PDAI Score") +
  theme(legend.position = "none") +
  scale_y_continuous(breaks = integer_breaks())

ggsave("../figures/pdai_score.png", device = "png", width = 6, height = 6)
  
```


```{r}
fmt_remission <- x %>% 
  select(id, group, stage, pdai_score) %>% 
  pivot_wider(names_from = stage, values_from = pdai_score) %>% 
  mutate(
    diff = Before - After,
    remission = if_else(
      After < 7, TRUE, FALSE
    )
  ) %>% 
  filter(remission, group == "FMT")


m_pt %>%
  filter(project == "MP", id %in% fmt_remission$id) %>% 
  filter(stage %in% c("treatment_5", "treatment_10", "treatment_15", "treatment_21"),
         !is.na(group)) %>% 
  select(id, stage, project, group, donor) %>%
  mutate(
    stage_number = as.double(str_extract(stage, "[0-9]+")),
    donor_round = case_when(
      stage_number <= 5 ~ "round 1",
      stage_number <= 10 ~ "round 2",
      stage_number <= 15 ~ "round 3",
      stage_number <= 21 ~ "round 4",
    )
  ) %>% 
  mutate(donor = parse_number(donor)) %>% 
  ggplot(aes(x = donor_round, y = id, fill = as.factor(donor), label = donor)) + 
  geom_tile(color="white") + 
  facet_grid(~project) + 
  geom_text(check_overlap = T) + 
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))

```




## correlation bewtween PDAI and ext_conc

```{r}
m_pt %>% 
  filter(stage %in% c("inclusion", "followup_30d"),
         project == "MP") %>% 
  ggplot(aes(x = dna_conc, y = pdai_score, color = stage, shape = stage)) +
  #geom_line(aes(group = id), color = "black") +
  geom_point(size = 3) + 
  scale_y_continuous(breaks = integer_breaks())
```



## Treatment retention time
```{r}

m_all <- read_delim("../data/metadata/metadata.csv", delim = ";", show_col_types = FALSE, col_types = list(batch_3 = col_double()))


m_treatment <- m_all %>% 
  select(id, sample_barcode, group, project, treatment_time:treatment_length, stage) %>% 
  filter(project == "MP") %>% 
  filter(!is.na(treatment_length)) %>% 
  mutate(
    stage_number = as.double(str_extract(stage, "[0-9]+")),
    donor_round = case_when(
      stage_number <= 5 ~ "round 1",
      stage_number <= 10 ~ "round 2",
      stage_number <= 15 ~ "round 3",
      stage_number <= 21 ~ "round 4",
    )
  )



treatment_time_median <- m_treatment %>% 
  group_by(group) %>% 
  summarise(
    median = median(treatment_length),
    mean = mean(treatment_length),
    sd = sd(treatment_length)
  ) %>% 
  mutate(
    label = paste0(
      "mean: ", round(mean,1), "\n",
      "sd: ", round(sd,1), "\n",
      "median: ", median
    ),
    id = case_when(
      group == "FMT" ~ "pt005",
      group == "placebo" ~ "pt003"
    )
  )



m_treatment %>%
  ggplot(aes(x = id, y = treatment_length)) +
    geom_boxplot() + 
    geom_point(position = position_jitter(width = 0.2), alpha = 0.5) + #aes(color = donor_round)
    plot_theme +
    geom_label(
      data = treatment_time_median, aes(y = 200, label = label)
    ) +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 0.9, hjust = 0.9)
    ) +
    facet_grid(. ~group, scales = "free") +
    labs(y = "Treatment Retention Time [min]")

ggsave("../figures/metadata/id_retention_time.png", width = 8)

# 
# 
# m_all %>% 
#   select(id, sample_barcode, group, project, treatment_time:treatment_length, stage) %>% 
#   filter(project == "MP") %>% 
#   filter(!is.na(treatment_time)) %>% 
#   mutate(
#     stage_number = as.double(str_extract(stage, "[0-9]+")),
#     donor_round = case_when(
#       stage_number <= 5 ~ "round 1",
#       stage_number <= 10 ~ "round 2",
#       stage_number <= 15 ~ "round 3",
#       stage_number <= 21 ~ "round 4",
#     )
#   ) %>%
#   ggplot(aes(x = stage_number, y = treatment_length)) +
#     # geom_boxplot() + 
#     geom_point(aes(color = donor_round), position = position_jitter(width = 0.2), alpha = 0.5) +
#     # geom_line(aes(group = id), color = "gray80", linetype = "dashed", position = position_dodge(width = 0.2)) +
#     plot_theme +
#     theme(
#       axis.text.x = element_text(angle = 45, vjust = 0.9, hjust = 0.9)
#     ) +
#     facet_grid(.~group)


m_treatment %>%
  ggplot(aes(x = group, y = treatment_length)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_point(aes(color = donor_round), position = position_jitter(width = 0.2)) +
  plot_theme +
  geom_label(
    data = treatment_time_median, aes(y = 260,label = label)
  ) +
  theme(
    legend.position = "right"
  ) +
  labs(y = "Treatment Retention Time [min]", color = "Treatment Round")

ggsave("../figures/metadata/group_retention_time.png", width = 8)

```




