---
title: "Ordination plot"
author: "Sebastian Mølvang Dall"
date: '2022-08-24'
output: html_document
---


## libraries and functions

```{r}
library(tidyverse)
library(ampvis2)
library(RColorBrewer)
source("functions/metadata_functions.R")
source("functions/bioinformatics.R")
```


## Load data

```{r}
metadata <- load_metadata()

metaphlan <- load_metaphlan("fulltax_species")

project_filter = "NP"
```



### Prepare metadata

```{r}
metadata_in_metaplan <- prepare_metadata(metadata) %>% 
  filter(LibID %in% colnames(metaphlan))

metadata_MP <- prepare_metadata(metadata) %>%
  filter(LibID %in% colnames(metaphlan)) %>%
  IsolateProjectAndDonor(project_filter = "MP") %>% 
  relocate(LibID) %>% 
  mutate(sample_group = paste0(x_axis, " ",group),
         sample_group = if_else(str_detect(sample_group, "Donor FMT"), str_remove(sample_group, " FMT"), sample_group))
```


### Prepare tax data

```{r}
metaphlan_otu <- metaphlan %>%
 select(-NCBI_tax_id) %>%
 select(clade_name, metadata_MP$LibID) %>% 
 mutate(OTU = paste0("OTU",row_number())) %>% 
 relocate(OTU)


otutable <- metaphlan_otu %>% 
  select(-clade_name)


taxtable <- metaphlan_otu %>% 
  select(OTU, clade_name) %>% 
  separate(clade_name, sep = "\\|", into = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")) %>% 
  relocate(OTU, .after = "Species")
```


## Load ampvis


```{r}
d <- amp_load(
  otutable = otutable,
  metadata = metadata_MP,
  taxonomy = taxtable
)
```


### Filter ampvis for pre post

```{r}
stages = stages_pre_post

metadata_pre_post <- metadata_MP %>% 
  filter(x_axis %in% stages, x_axis != "Donor") %>% 
  group_by(id) %>%
  filter(n_distinct(x_axis) == 2) %>% 
  ungroup()
```

```{r}
d_pre_post <- d %>% 
  amp_subset_samples(LibID %in% metadata_pre_post$LibID)
```


### Ordination


```{r}


rda_ord_all <- d %>% 
  amp_subset_samples(LibID %in% metadata_pre_post$LibID | x_axis == "Donor") %>% 
  amp_ordinate(
  type = "rda",
  constrain = "sample_group",
  transform = "hellinger",
  sample_color_by = "sample_group",
  sample_colorframe = T
) + 
  labs(fill = "", color = "") +
  scale_color_brewer(palette = "Paired")
rda_ord_all

ggsave("../figures/amp_rda_hellinger_all.png", device = "png")
```


```{r}
pca <- d %>% 
  amp_subset_samples(LibID %in% metadata_pre_post$LibID | x_axis == "Donor") %>% 
  amp_ordinate(
  type = "ca",
  transform = "hellinger",
  sample_color_by = "sample_group",
  #sample_plotly = "id",
  sample_label_by = "id",
  species_plot = F,
  species_nlabels = 10,
  species_label_taxonomy = "Genus",
  filter_species = 0,
  sample_colorframe = F
) + 
  geom_line(aes(group = id), color = "grey70") +
  theme(legend.title = element_blank()) +
  scale_color_brewer(palette = "Paired")

pt014_do016 <- pca$data %>% 
  filter(id == "pt014" & x_axis == "Post" | donor_batch == "do016_4")
pca +
  geom_text(data = pt014_do016, aes(x = PC1, y = PC2+0.04, label = id), color = "red", size = 3)

#ggsave("../figures/amp_ca_hellinger_all.png", device = "png", width = 7, height = 5)
```



```{r}
do_extreme <- pca$data %>% 
  filter(PC2 > 0.2, x_axis == "Donor")
```

```{r}
paired_2_5 = brewer.pal(n = 5, "Paired")[2:5]

rda_ord_pt <- d_pre_post %>% 
  #amp_filter_samples(x_axis == "Post") %>% 
  amp_ordinate(
  
  type = "rda",
  constrain = "sample_group",
  transform = "hellinger",
  sample_color_by = "sample_group",
  sample_colorframe = T,
  #sample_colorframe_label = "sample_group",
  species_plot = F,
  envfit_factor = "sample_group",
  envfit_show = T,
  detailed_output = T
)

rda_ord_pt$plot +
  labs(fill = "", color = "") +
  scale_color_manual(values = paired_2_5) +
  scale_fill_manual(values = paired_2_5) +
  theme(legend.position = "none")

rda_ord_pt$evf_factor_model

#ggsave("../figures/amp_rda_hellinger_no_donor.png", device = "png")
```

```{r}
t_metaphlan <- metaphlan %>% 
  dplyr::select(!NCBI_tax_id) %>% 
  pivot_longer(-clade_name, names_to = "LibID") %>% 
  pivot_wider(names_from = clade_name, values_from = value) %>% 
  filter(LibID %in% metadata_pre_post$LibID) %>% 
  arrange(LibID) %>% 
  column_to_rownames("LibID") %>% 
  abundance_filter(abundance_threshold = 10^-34) %>% 
  vegan::decostand("hellinger") %>% 
  rownames_to_column("LibID")


MetadataMetaphlan <- metadata_pre_post %>% 
  dplyr::select(LibID) %>% 
  ungroup() %>% 
  left_join(t_metaphlan) %>% 
  column_to_rownames("LibID") %>% 
  as.data.frame()

constrain <- metadata_pre_post %>%
  arrange(LibID) %>% 
  select(sample_group) 
  


RDA <- rda(MetadataMetaphlan ~ sample_group, data = constrain)

envfit(RDA, env = constrain)

R2.obs <- RsquareAdj (RDA)$r.squared
set.seed(1)
anova(RDA, permutations = 999, by = "margin")

```

```{r}

n.perm <- 999  # set the number of permutations
R2.rand <- replicate (n = n.perm, expr = {
  constrain.rand <- constrain %>% 
    sample_n(nrow(constrain))
  RDA.rand <- rda(MetadataMetaphlan ~ sample_group, data = constrain.rand)
  RsquareAdj (RDA.rand)$r.squared
})

R2 <- c (R2.rand, R2.obs)

hist (R2, nclass = 100)  # ; argument "nclass" separates the bars into 100 categories (compare with hist without this argument)
abline (v = R2.obs, col = 'red')

```

```{r}
permutations = 1000
set.seed(1)

metadata_test <- metadata_pre_post %>% 
  filter(group == "FMT")

t_metaphlan <- metaphlan %>% 
  dplyr::select(!NCBI_tax_id) %>% 
  pivot_longer(-clade_name, names_to = "LibID") %>% 
  pivot_wider(names_from = clade_name, values_from = value) %>% 
  filter(LibID %in% metadata_test$LibID) %>% 
  arrange(LibID) %>% 
  column_to_rownames("LibID") %>% 
  abundance_filter(abundance_threshold = 10^-34) %>% 
  vegan::decostand("hellinger")

dist <- t_metaphlan %>% 
  vegdist()

dist_metadata <- metadata_test %>% 
  select(LibID, group, x_axis, sample_group) %>% 
  arrange(LibID)

adonis2(dist~sample_group,
                   data = dist_metadata,
                   permutations = permutations,
        by = "terms")
```


## NP and MP donor PCA

```{r}
metadata_NP <- prepare_metadata(metadata) %>%
  filter(LibID %in% colnames(metaphlan)) %>%
  IsolateProjectAndDonor(project_filter = "NP") %>% 
  relocate(LibID) %>% 
  mutate(sample_group = paste0(x_axis, " ",group),
         sample_group = if_else(str_detect(sample_group, "Donor FMT"), str_remove(sample_group, " FMT"), sample_group),
         project = "NP")

metadata_MP <- prepare_metadata(metadata) %>%
  filter(LibID %in% colnames(metaphlan)) %>%
  IsolateProjectAndDonor(project_filter = "MP") %>% 
  relocate(LibID) %>% 
  mutate(sample_group = paste0(x_axis, " ",group),
         sample_group = if_else(str_detect(sample_group, "Donor FMT"), str_remove(sample_group, " FMT"), sample_group),
         project = "MP")

metadata_NP_MP <- bind_rows(metadata_MP, metadata_NP) %>% 
  mutate(sample_group = paste0(sample_group, " ", project))

```

```{r}
metaphlan_otu <- metaphlan %>%
 select(-NCBI_tax_id) %>%
 select(clade_name, metadata_NP_MP$LibID) %>% 
 mutate(OTU = paste0("OTU",row_number())) %>% 
 relocate(OTU)


otutable <- metaphlan_otu %>% 
  select(-clade_name)


taxtable <- metaphlan_otu %>% 
  select(OTU, clade_name) %>% 
  separate(clade_name, sep = "\\|", into = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")) %>% 
  relocate(OTU, .after = "Species")


d <- amp_load(
  otutable = otutable,
  metadata = metadata_NP_MP,
  taxonomy = taxtable
)
```


```{r}
stages = stages_pre_post

metadata_NP_MP_stages <- metadata_NP_MP %>% 
  filter(x_axis %in% stages)

d_subset <- d %>% 
  amp_subset_samples(LibID %in% metadata_NP$LibID | x_axis == "Donor", x_axis %in% stages, id != "pt002")
```



```{r}
d_subset %>% 
  amp_ordinate(
  type = "pca",
  transform = "hellinger",
  sample_color_by = "sample_group",
  species_plot = T,
  species_nlabels = 7,
  species_label_taxonomy = "Genus",
  sample_shape_by = "x_axis"
) + 
  geom_line(aes(group = id), color = "grey70") +
  theme(legend.title = element_blank()) +
  scale_color_brewer(palette = "Paired")

ggsave("../figures/NP_PCA.png", device = "png", width = 6, height = 6)


```

```{r}
d_subset %>% 
  amp_heatmap(tax_show = 35,
              normalise = F,
              tax_aggregate = "Genus")
```

